# Render.yaml configuration file
services:
  # Web service for the frontend and WebSocket server
  - type: web
    name: king-of-the-bay
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python websocket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    # Ensure WebSockets are enabled
    websocket: true
    # Use port 10000 for WebSocket server
    port: 10000
